Repository AppFitnessTeam/project-fitness-constructor, pull requests merged in 2022-08, with the labels that each got.

#28 Bottom navigation view
  app/build.gradle
  app/src/main/java/com/example/fitnessconstructor/ui/MainActivity.kt
  app/src/main/java/com/example/fitnessconstructor/ui/SplashFragment.kt
  app/src/main/java/com/example/fitnessconstructor/ui/workout/WorkoutFragment.kt
  app/src/main/res/drawable/ic_bottom_menu_any.xml
  app/src/main/res/drawable/ic_bottom_menu_settings.xml
  app/src/main/res/drawable/ic_bottom_menu_statistic.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_app_settings.xml
  app/src/main/res/layout/fragment_bottom_navigation.xml
  app/src/main/res/layout/fragment_splash.xml
  app/src/main/res/layout/fragment_statistic.xml
  app/src/main/res/layout/fragment_workout.xml
  app/src/main/res/layout/fragment_workout_list.xml
  app/src/main/res/menu/menu_bottom_navigation.xml
  app/src/main/res/navigation/navigation_graphs.xml
  app/src/main/res/values-night/strings.xml
  app/src/main/res/values/strings.xml
Labels: arch, dev

#23 add design link into README.md
  README.md
Labels: doc

#27 Fix StressUseCaseImpl
  app/src/main/java/com/example/fitnessconstructor/data/StressUseCaseImpl.kt
  app/src/test/java/com/example/fitnessconstructor/StressUseCaseUnitTest.kt
Labels: dev
